inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 1500
Metrics/ModuleLength:
  Max: 1500
